apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-jswiki
spec:
  ingressClassName: nginx
  rules:
    - host: wiki.jun-sisters.gay
      http:
        paths:
          - backend:
              service:
                name: jswiki
                port:
                  number: 80
            path: /
            pathType: Prefix
